modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "Apache 2.0"

[[mods]]
modId = "vs_addon"
version = "${version}"
displayName = "VS Addon"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.vs_addon]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_addon]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_addon]]
modId = "architectury"
mandatory = true
versionRange = "[4.12.94,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vs_addon]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2.1.1-beta.5,)"
ordering = "AFTER"
side = "BOTH"
